version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: calorie_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: calories_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: calorie_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:securepassword@db:5432/calories_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: calorie_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: